package com.hckcapital.be.model;

import lombok.Data;
import org.bson.types.ObjectId;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDateTime;
import java.util.Date;
import java.util.List;

@Data
@Document(collection = "cards")
public class Card {

    // ── Nested types ─────────────────────────────────────────────────────────────

    @Data
    public static class DeleteInfo {
        private Boolean isDeleted;
        private Date deletedDate;
    }

    @Data
    public static class ViewDetail {
        private String viewerId;
        private Date viewedAt;
    }

    @Data
    public static class UpdateHistoryEntry {
        private ObjectId profileId;
        private Date timestamp;
    }

    // ── Fields ────────────────────────────────────────────────────────────────────

    @Id
    private String id;

    /** Secondary unique string identifier generated by the editor. */
    private String cardID;

    /** ObjectId ref → profiles collection. */
    private ObjectId creator;

    private String title;

    /** Stored as "PUBLIC" or "PRIVATE" in MongoDB — kept as String to avoid enum-name mismatch. */
    private String status;

    private String description;

    /** Profile ObjectIds that liked this card. */
    private List<ObjectId> likes;

    /** Profiles credited for the LIKE_CARDS mission — prevents re-crediting on like/unlike cycling. */
    private List<ObjectId> likeMissionCreditedBy;

    /** Profile ObjectIds that follow/bookmarked this card. */
    private List<ObjectId> followers;

    private List<String> categories;

    /** ObjectId ref → components collection (legacy). */
    private ObjectId components;

    /** ObjectId ref → components collection (LINE Flex JSON). */
    private ObjectId lineFormatComponent;

    /** ObjectId ref → components collection (HTML render). */
    private ObjectId flexFormatHtml;

    private Integer totalViews;

    private Integer shareCount;

    private Boolean isReadyToPublish;

    private Boolean isContainingVideo;

    private DeleteInfo deleteInfo;

    /** ObjectId refs → comments collection. */
    private List<ObjectId> comments;

    private List<ViewDetail> viewDetails;

    private List<UpdateHistoryEntry> updateHistory;

    /** Localised share titles, one entry per language. */
    private List<String> cardShareTitle;

    // ── Timestamps (set by { timestamps: true } in Mongoose) ──────────────────────

    private LocalDateTime createdAt;

    private LocalDateTime updatedAt;
}
